=== ifunsoftware/c3-next/c3-remote/WebContent/rest.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://c3.aphreet.org/rest/1.0"
           xmlns="http://c3.aphreet.org/rest/1.0">

    <xs:element name="result">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="version" type="xs:string"/>
                <xs:element name="resource" type="resourceType" maxOccurs="1"/>
                <xs:element name="searchResults" type="searchResultsType" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="resourceType">
        <xs:sequence>
            <xs:element name="metadata" type="metadataType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="systemMetadata" type="metadataType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="versions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="version" type="versionType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="address" type="xs:string" use="required"/>
        <xs:attribute name="createDate" type="xs:dateTime" use="required"/>
        <xs:attribute name="trackVersions" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:complexType name="metadataType">
        <xs:sequence>
            <xs:element name="element" type="elementType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="elementType">
        <xs:sequence>
            <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="versionType">
        <xs:sequence>
            <xs:element name="systemMetadata" type="metadataType" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:dateTime" use="required"/>
    </xs:complexType>

    <xs:complexType name="searchResultsType">
        <xs:sequence>
            <xs:element name="entry" type="searchResultEntryType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="searchResultEntryType">
        <xs:sequence>
            <xs:element name="fragments" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="string" type="xs:string" minOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="address" type="xs:string" use="required"/>
        <xs:attribute name="score" type="xs:decimal" use="required"/>
    </xs:complexType>

</xs:schema>

=== ifunsoftware/c3-next/c3-remote/WebContent/resource.xml
<?xml version="1.0" encoding="UTF-8"?>
<result xmlns="http://c3.aphreet.org/rest/1.0"
        xsi:schemaLocation="http://c3.aphreet.org/rest/1.0 http://c3-system.googlecode.com/files/rest.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <version>1.0</version>
    <resource address="my_resource_address" createDate="2011-02-07 17:55:10.836 MSK" trackVersions="false">
        <metadata>
            <element key="md_key">
                <value>sdsd</value>
            </element>
            <element key="md_key2">
                <value>md&quot;value2</value>
            </element>
        </metadata>
        <systemMetadata/>
        <versions>
            <version date="2011-02-07 17:55:11.55 MSK">
                <systemMetadata>
                    <element key="sys_key">
                        <value>sys_value</value>
                    </element>
                </systemMetadata>
            </version>
        </versions>
    </resource>
</result>
